#!/bin/bash
RUN_COMMAND="./bin/Interpreter"
INPUTS_DIR="./weak_tests"
OUTPUTS_DIR="./tests_results"

# test invalid inputs
for INDEX in `seq 1 5`
do
	INVALID_INPUT="/bad"
	OUTPUT="/badout"
	CODEEXTENSION=".code"
	DATAEXTENSION=".data"
	EXPECTEXTENSION=".expected"
	echo ">>>INVALID_TESTCASE #$INDEX"
	$RUN_COMMAND $INPUTS_DIR$INVALID_INPUT$INDEX$CODEEXTENSION $INPUTS_DIR$INVALID_INPUT$INDEX$DATAEXTENSION  $OUTPUTS_DIR$OUTPUT$INDEX
	echo $
	#echo "$RUN_COMMAND $INPUTS_DIR$VALID_INPUT$INDEX$CODEEXTENSION $INPUTS_DIR$VALID_INPUT$INDEX$DATAEXTENSION  $OUTPUTS_DIR$OUTPUT$INDEX"
done

# test valid inputs
for INDEX in `seq 1 4`
do
	VALID_INPUT="/t"
	OUTPUT="/validout"
	CODEEXTENSION=".code"
	DATAEXTENSION=".data"
	EXPECTEXTENSION=".expected"
	echo ">>>VALID_TESTCASE #$INDEX"
	$RUN_COMMAND $INPUTS_DIR$VALID_INPUT$INDEX$CODEEXTENSION $INPUTS_DIR$VALID_INPUT$INDEX$DATAEXTENSION  $OUTPUTS_DIR$OUTPUT$INDEX
	diff $OUTPUTS_DIR$OUTPUT$INDEX $INPUTS_DIR$VALID_INPUT$INDEX$EXPECTEXTENSION
	echo $
	#echo "$RUN_COMMAND $INPUTS_DIR$VALID_INPUT$INDEX$CODEEXTENSION $INPUTS_DIR$VALID_INPUT$INDEX$DATAEXTENSION  $OUTPUTS_DIR$OUTPUT$INDEX"
done